services:
  traefik:
    image: traefik:latest
    container_name: nekocafe-traefik
    restart: unless-stopped
    command: ["--configFile=/etc/traefik/traefik.yml"]
    volumes:
      - ./infra/cd/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./infra/cd/traefik/dynamic:/etc/traefik/dynamic:ro
    ports:
      - "8080:8080"
      - "8089:8089"
    depends_on:
      - reservation-stable
      - reservation-canary
      - member

  reservation-stable:
    build: ./services/reservation
    container_name: nekocafe-reservation-stable
    restart: unless-stopped
    environment:
      SERVICE_NAME: reservation-service
      SERVICE_VERSION: v1.0.0
      RELEASE_CHANNEL: stable
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: reservation
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      EVENT_BUS_MODE: outbox
      EVENT_BUS_NAME: rocketmq
      ACCESS_LOG_LEVEL: info
      OTEL_SDK_DISABLED: ${OTEL_SDK_DISABLED:-false}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://otel-collector:4318}
      OTEL_PROMETHEUS_PORT: 9464
      INJECT_LATENCY_MS: 0
      ERROR_RATE_PERCENT: 0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  reservation-canary:
    build: ./services/reservation
    container_name: nekocafe-reservation-canary
    restart: unless-stopped
    environment:
      SERVICE_NAME: reservation-service
      SERVICE_VERSION: v1.1.0-canary
      RELEASE_CHANNEL: canary
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: reservation
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      EVENT_BUS_MODE: outbox
      EVENT_BUS_NAME: rocketmq
      ACCESS_LOG_LEVEL: info
      OTEL_SDK_DISABLED: ${OTEL_SDK_DISABLED:-false}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://otel-collector:4318}
      OTEL_PROMETHEUS_PORT: 9464
      INJECT_LATENCY_MS: ${CANARY_INJECT_LATENCY_MS:-0}
      ERROR_RATE_PERCENT: ${CANARY_ERROR_RATE_PERCENT:-0}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
