http:
  services:
    reservation-rollout:
      weighted:
        services:
          - name: reservation-stable
            weight: 100
          - name: reservation-canary
            weight: 0

    reservation-stable:
      loadBalancer:
        servers:
          - url: "http://reservation-stable:8080"

    reservation-canary:
      loadBalancer:
        servers:
          - url: "http://reservation-canary:8080"
